### ISSUE TITLE
how to execute

### ISSUE THREAD

**Issue by iam-raheem** [donnykurnia/Railscasts-downloader#4]
hello,
i want to know how to execute this script & download all vidoes.
Plz help me.

**Comment by donnykurnia** [comment]
Hi @srinu0541 

Basically you just need to download railscasts-downloader.rb file and put this into your computer. Before run it, make sure you already have nokogiri gem installed:

```
gem install nokogiri
```

Then run this file using this command:

```
ruby railscasts-downloader.rb
```

Or make it executable so you could run it directly:

```
chmod +x railscasts-downloader.rb
./railscasts-downloader.rb
```

FYI, I haven't get a chance to update this script to handle pro and revisited episodes. You could check the forks of this script and try the one that have handled this correctly.

Thanks,

**Comment by iam-raheem** [comment]
thank you so much for the script. It is downloading all the free episodes. But we need to get PRO episodes also. I'll try my level best to get those too & update here.
